package com.tlias.mapper;

import com.tlias.pojo.Emp;
import com.tlias.pojo.EmpQueryParam;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.MapKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;

import java.util.List;
import java.util.Map;

@Mapper
public interface EmpMapper {

    /**
     * Counts the total number of employees by performing a left join between the emp table
     * and the dept table based on the department ID.
     * Apply LIMIT with range for pagination.
     * @return the total count of employees as a Long value
     */
//    @Select("select count(*) from emp e left join dept d on e.dept_id = d.id")
//    Long countEmp();
//
//    @Select("""
//        SELECT e.*,
//               d.name AS deptName
//        FROM emp e
//        LEFT JOIN dept d ON e.dept_id = d.id
//        ORDER BY e.update_time DESC
//        LIMIT #{start}, #{pageSize}
//        """)
//    List<Emp> findPageEmp(Integer start, Integer pageSize);

    /**
     * Select all rows for pagination.
     * No need to apply LIMIT because we use pageHelper in this case.
     *
     * @return list of employees
     */
//    @Select("""
//            SELECT e.*,
//                   d.name AS deptName
//            FROM emp e
//                     LEFT JOIN dept d ON e.dept_id = d.id
//            ORDER BY e.update_time DESC
//            """)
//    List<Emp> list(String name, Integer gender, LocalDate begin, LocalDate end);

    /**
     * Select employees for pagination based on criteria.
     * @param empQueryParam object that wraps the employee query param.
     * @return Emp list
     */
    List<Emp> list(EmpQueryParam empQueryParam);

    /**
     * save employee's basic information to the emp table.
     * @param emp wrapper object to store employee info.
     */
    @Options(useGeneratedKeys = true, keyProperty = "id") // id will be auto-generated by database.and set to the emp object.
    @Insert("insert into emp(username, name, gender, phone, job, salary, image, entry_date, dept_id, create_time, update_time) " +
            "values(#{username}, #{name}, #{gender}, #{phone}, #{job}, #{salary}, #{image}, #{entrydate},#{deptId}, #{createTime}, #{updateTime})")
    void addEmp(Emp emp);

    /**
     * 统计员工职位人数
     */
    /*可能存在MybatisX插件误报 不用在意 或者在设置中编辑器中找到Mybatis选项关闭 或者添加上mapkey注解选项无报错不添加也行*/
    @MapKey("pos")
    List<Map<String,Object>> countEmpJobData();

    /**
     * 统计员工性别人数
     * @return
     */
    @MapKey("gender")
    List<Map<String, Object>> countEmpGenderData();

}
